# Generated by Django 4.2.27 on 2026-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peticiones_volver',
            field=models.PositiveIntegerField(default=0, verbose_name='Interesados en reponer'),
        ),
    ]
