# Generated by Django 4.2.27 on 2026-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_peticiones_volver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Sugerencia de Producto'), ('CRITICA', 'Crítica/Mejora'), ('FELICITACION', 'Felicitación'), ('OTRO', 'Otro')], default='PRODUCTO', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre (Opcional)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo (Opcional)')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sugerencias/', verbose_name='Imagen de referencia')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Buzón de Sugerencias',
            },
        ),
    ]
