# Generated by Django 4.2.27 on 2026-04-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_sugerencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sugerencia',
            options={'verbose_name': 'Sugerencia', 'verbose_name_plural': 'Buzón de Sugerencias'},
        ),
    ]
