# Generated by Django 4.2.27 on 2026-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ip_dinamica_tienda',
            field=models.CharField(blank=True, help_text='IP de la tienda auto-actualizada de forma dinámica', max_length=45, null=True),
        ),
    ]
