# Generated by Django 4.2.27 on 2026-06-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_configuracionsistema_ip_dinamica_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Sube tu archivo de Excel (.xlsx) aquí', upload_to='importaciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importar Excel',
                'verbose_name_plural': 'Importador de Excels',
            },
        ),
    ]
